{
 "title": "Minio 监控",
 "description": "Minio 监控面板（中文版，支持多个机器监控）\n主要监控信息",
 "tags": [ "object-storage" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "instance", "label": "实例名", "query": "minio_version_info" },
   {
    "name": "metrics_port",
    "label": "Minio 地址",
    "query": "label_values(minio_total_disks,instance)"
   },
   {
    "name": "interval",
    "label": "间隔时间",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "description": "Minio is a high performance distributed object storage server, designed for large-scale private cloud infrastructure. For more information, check out the docs.",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "content": "<img src=\"https://min.io/resources/img/logo/MINIO_wordmark.png\" style=\"height: 55px;\"></img>"
  },
  {
   "title": "统计时间",
   "type": "singlestat",
   "description": "Start time of the Minio server",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "format": "dtdurations",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds)",
     "legendFormat": "Start time of the Minio server"
    }
   ]
  },
  {
   "title": "硬盘数据情况",
   "type": "graph",
   "description": "Number of total/offline disks for current MinIO server instances",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "minio_offline_disks{instance=~\"$metrics_port\"}",
     "legendFormat": "Offline {{instance}}"
    },
    {
     "expr": "minio_total_disks{instance=~\"$metrics_port\"}",
     "legendFormat": "Total {{instance}}"
    }
   ]
  },
  {
   "title": "硬盘使用率",
   "type": "graph",
   "description": "Storage space usage",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "minio_disk_storage_used_bytes{instance=~\"$metrics_port\"}",
     "legendFormat": "used {{instance}}"
    },
    {
     "expr": "minio_disk_storage_total_bytes{instance=~\"$metrics_port\"}",
     "legendFormat": "total {{instance}}"
    }
   ]
  },
  {
   "title": "磁盘总数",
   "type": "singlestat",
   "description": "Total number of disks for current MinIO server instances",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 2 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(minio_total_disks)",
     "legendFormat": "Total number of disks for current MinIO server instances"
    }
   ]
  },
  {
   "title": "离线磁盘数",
   "type": "singlestat",
   "description": "Total number of offline disks for current MinIO server instances",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 2 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(minio_offline_disks)",
     "legendFormat": "Total number of offline disks for current MinIO server instances"
    }
   ]
  },
  {
   "title": "数据传输(KB/s)",
   "type": "graph",
   "description": "Data sent by current Minio server instance",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(minio_network_sent_bytes_total{instance=\"$metrics_port\"}[5m])",
     "legendFormat": "Transmited:"
    }
   ]
  },
  {
   "title": "数据接收(KB/s)",
   "type": "graph",
   "description": "Data received by current Minio server instance",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(minio_network_received_bytes_total{instance=\"$metrics_port\"}[5m])",
     "legendFormat": "Received:"
    }
   ]
  },
  {
   "title": "网络输入/输出(KB/s)",
   "type": "graph",
   "description": "Data received x transmited by current Minio server instance",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(minio_network_received_bytes_total{instance=\"$metrics_port\"}[5m])",
     "legendFormat": "Received: "
    },
    {
     "expr": "rate(minio_network_sent_bytes_total{instance=\"$metrics_port\"}[5m])",
     "legendFormat": "Transmited:"
    }
   ]
  },
  {
   "title": "CPU 使用率",
   "type": "graph",
   "description": "Total user and system CPU time spent in seconds",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=~\"$metrics_port\"}[$interval])",
     "legendFormat": "Total CPU {{instance}}"
    }
   ]
  },
  {
   "title": "HTTP 请求持续时间 duration/s",
   "type": "graph",
   "description": "The current aggregate time spent servicing all HTTP requests  in seconds",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(minio_http_requests_duration_seconds_sum{request_type=\"GET\",instance=\"$metrics_port\"}[5m])",
     "legendFormat": "GET"
    },
    {
     "expr": "rate(minio_http_requests_duration_seconds_sum{request_type=\"POST\",instance=\"$metrics_port\"}[5m])",
     "legendFormat": "POST"
    },
    {
     "expr": "rate(minio_http_requests_duration_seconds_sum{request_type=\"PUT\",instance=\"$metrics_port\"}[5m])",
     "legendFormat": "PUT"
    },
    {
     "expr": "rate(minio_http_requests_duration_seconds_sum{request_type=\"HEAD\",instance=\"$metrics_port\"}[5m])",
     "legendFormat": "HEAD"
    },
    {
     "expr": "rate(minio_http_requests_duration_seconds_sum{request_type=\"DELETE\",instance=\"$metrics_port\"}[5m])",
     "legendFormat": "DELETE"
    }
   ]
  }
 ]
}